import numpy as np
import numpy.typing
import numpy

class RustSABBlock:
    rep_id: int
    dim: int
    e: int
    orbit_reps_flat: list[int]
    orbit_sizes: list[int]
    valid_cols: np.ndarray
    j_values: np.ndarray
    l_values: np.ndarray

class RustSABTransform:
    blocks: list[RustSABBlock]
    n_monomials: int

    def extract_batch(
        self,
        batch_data: list[np.ndarray],
        batch_indices: list[np.ndarray],
        batch_indptr: list[np.ndarray],
    ) -> list[list[tuple[np.ndarray, np.ndarray, np.ndarray, int]]]: ...

def build_sab_blocks(
    orbits: list[tuple[int, ...]],
    paths: dict[int, list[tuple[int, list[int], int]]],
    g_inv_data: dict[int, list[int]],
    n: int,
    d: int,
    e: int,
    is_squarefree: bool,
    total_monomials: int,
    coset_actions: dict[int, numpy.typing.NDArray[numpy.uint32]] | None = None,
    coset_actions_inv: dict[int, numpy.typing.NDArray[numpy.uint32]] | None = None,
) -> RustSABTransform: ...
def compute_fs_and_t_data(
    paths: dict[int, list[tuple[int, list[int], int]]],
    orbits: list[tuple[int, ...]],
    is_squarefree: bool,
    n: int,
    d: int,
    coset_actions: dict[int, numpy.typing.NDArray[numpy.uint32]],
    rep_types: dict[int, int],
) -> tuple[
    dict[int, int], dict[int, dict[tuple[int, ...], tuple[float, list[int]]]]
]: ...

class PcGroup:
    number_of_generators: int
    orders: list[int]
    conjugation_exponents: dict[tuple[int, int], int]
    power_tails: dict[int, list[tuple[int, int]]]
    conjugation_tails: dict[tuple[int, int], list[tuple[int, int]]]
    generators: list[list[int]]

    def __init__(
        self,
        number_of_generators: int,
        orders: list[int],
        conjugation_exponents: dict[tuple[int, int], int],
        power_tails: dict[int, list[tuple[int, int]]],
        conjugation_tails: dict[tuple[int, int], list[tuple[int, int]]],
        generators: list[list[int]],
    ) -> None: ...

class PyOrbitLifter:
    def __init__(self, group: PcGroup, d: int, is_squarefree: bool) -> None: ...
    def clear_cache(self) -> None: ...
    def canonicalize(self, monomial: list[int]) -> list[int]: ...

class Permutation:
    def __init__(self, data: list[int] | tuple[int, ...]) -> None: ...
    @classmethod
    def identity(cls, n: int) -> Permutation: ...
    @property
    def data(self) -> tuple[int, ...]: ...
    @property
    def size(self) -> int: ...
    def __getitem__(self, index: int) -> int: ...
    def __mul__(self, other: Permutation) -> Permutation: ...
    def __pow__(self, p: int) -> Permutation: ...
    def __invert__(self) -> Permutation: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __getnewargs__(self) -> tuple[list[int]]: ...

class MonomialMatrix:
    def __init__(
        self,
        perm: list[int] | tuple[int, ...],
        vals: list[int] | tuple[int, ...],
        e: int,
    ) -> None: ...
    @classmethod
    def identity(cls, dim: int, e: int) -> MonomialMatrix: ...
    @property
    def perm(self) -> tuple[int, ...]: ...
    @property
    def vals(self) -> tuple[int, ...]: ...
    @property
    def e(self) -> int: ...
    @property
    def dim(self) -> int: ...
    def __add__(self, other: MonomialMatrix) -> MonomialMatrix: ...
    def __matmul__(self, other: MonomialMatrix) -> MonomialMatrix: ...
    def __pow__(self, p: int) -> MonomialMatrix: ...
    def inverse(self) -> MonomialMatrix: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __getnewargs__(self) -> tuple[list[int], list[int], int]: ...
